name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install protobuf-compiler
      
    - name: Generate C++ code
      run: |
        mkdir upload
        protoc --cpp_out=upload wv_proto2.proto
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Linux-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        include-hidden-files: true
        retention-days: 0
